Add controllers
vladislavStel/java-shareit pull request #1
Opened 2023-06-10 18:08 UTC by vladislavStel

2023-06-11 20:47 UTC, sergeymamonov requested changes

2023-06-11 20:47 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    Collection<User> findAll();
Здесь действительно необходимо отдавать интерфейс Collection? Это достаточно общий интерфейс, то есть это может быть и массив и множество.

2023-06-11 20:47 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private final Map<Long, String> userIdEmail = new HashMap<>();
Необходимости в этой структуре данных нет. Единственное, где она используется (кроме положить/удалить), это в методе isEmailExist. Но в этом методе используется containsValue, а это полный проход по мапе. Поэтому эта мапа не приводит к ускорению работы, только излишнее дублирование данных.

2023-06-11 23:17 UTC, vladislavStel commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    Collection<User> findAll();
изменил на List

2023-06-11 23:18 UTC, vladislavStel commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private final Map<Long, String> userIdEmail = new HashMap<>();
Убрал лишнюю мапу, метод isEmailExist переделан

2023-06-13 03:44 UTC, sergeymamonov approved these changes

2023-06-13 07:01 UTC, merged