Add bookings
vladislavStel/java-shareit pull request #2
Opened 2023-06-29 07:44 UTC by vladislavStel

2023-06-29 15:17 UTC, sergeymamonov requested changes

2023-06-29 15:17 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Pageable page = PageRequest.of(0, 500, Sort.by("start").descending());
Размер лучше вынести в константу. Только зачем вы здесь определяете пагинацию, если в контроллере (в API) не определена пагинация.

2023-06-29 15:17 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            addLastAndNextBookings(i);
Внутри этого метода выполняются запросы к БД в цикле. Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-06-29 15:17 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(s -> s.getStatus().equals(StatusBooking.APPROVED))
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте во всем коде, как вызывается метод equals.

2023-06-29 15:17 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    boolean validateUserById(Long userId);
Результат этого метода нигде не используется, поэтому можно изменить на void.

2023-06-29 17:58 UTC, vladislavStel commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Pageable page = PageRequest.of(0, 500, Sort.by("start").descending());
Добавил в API пагинацию. Теперь константа не нужна. Сделал просто потому что так красивее))

2023-06-29 18:58 UTC, vladislavStel commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(s -> s.getStatus().equals(StatusBooking.APPROVED))
В данном месте, если bookings не null и не пустой, то NPE в equals не будет, т.к. значение Status в БД теперь - NOT NULL.

2023-06-29 18:59 UTC, vladislavStel commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            addLastAndNextBookings(i);
Устранил

2023-06-29 18:59 UTC, vladislavStel commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    boolean validateUserById(Long userId);
Готово

2023-06-30 19:56 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(s -> s.getStatus().equals(StatusBooking.APPROVED))
Если можно обезопасить себя, то почему не обезопасить? StatusBooking.APPROVED - это константа, она никогда не будет равна null. Поэтому проще поменять и не думать.

2023-06-30 19:57 UTC, sergeymamonov approved these changes

2023-07-03 11:10 UTC, merged