Add docker
vladislavStel/java-shareit pull request #4
Opened 2023-07-22 13:15 UTC by vladislavStel

2023-07-23 09:00 UTC, sergeymamonov requested changes
BookingCreateDto есть аннотация FieldDefaults и модификатор private для id. В данном случае модификатор избыточен.

Валидация типа @PositiveOrZero и аналогичные нужно тоже удалить в контроллерах основного сервиса.

А зачем в основном сервисе остался DateValidator, а не перенести его в gateway?

2023-07-23 09:00 UTC, sergeymamonov commented on gateway/.gitignore
> +target/
Файл гитигнор должен быть только один и лежать он должен в корне проекта. Так как у нас один репозиторий, то и файл должен быть один.

2023-07-23 09:00 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
Для схожих классов решения должны быть одинаковыми. А сейчас какие-то dto c аннотацией FieldDefaults, а это dto без этой аннотации.

2023-07-23 09:00 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleValidationExceptions(Exception e) {
Сравните строку 26 и строку 28.

2023-07-23 09:00 UTC, sergeymamonov commented on gateway/src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void shouldCreateBookingIfItemIdNull_ReturnStatus400() throws Exception {
Все тесты практически одинаковые, поэтому можно свести их одному параметризированному тесту. https://reflectoring.io/tutorial-junit5-parameterized-tests/ Но не настаиваю на этом изменении, это как предложение по улучшению.

2023-07-23 11:30 UTC, vladislavStel commented on gateway/.gitignore
> +target/
Устранено

2023-07-23 11:30 UTC, vladislavStel commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
Лишний файл, удален

2023-07-23 11:30 UTC, vladislavStel commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleValidationExceptions(Exception e) {
Устранено

2023-07-23 19:17 UTC, vladislavStel commented on gateway/src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void shouldCreateBookingIfItemIdNull_ReturnStatus400() throws Exception {
Добавил один параметризированный тест(вместо трех тестов). Прошу обратной связи. Смущает использование private класса для передачи тестовых объектов, но других вариантов я не нашел.

2023-07-24 06:44 UTC, sergeymamonov commented on gateway/src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void shouldCreateBookingIfItemIdNull_ReturnStatus400() throws Exception {
@ParameterizedTest в параметризированном тесте мы должны передавать какие-то параметры в тест. Посмотрите здесь https://reflectoring.io/tutorial-junit5-parameterized-tests/, какие способы есть для передачи параметров в тест, это может быть @ValueSource, @MethodSource и др. Пример, есть несколько тестов с различными значениями "from" и "size". Вот эти параметры и нужно передавать в тест.

2023-07-24 06:46 UTC, sergeymamonov approved these changes

2023-07-24 07:50 UTC, merged